apiVersion: v1
kind: Service
metadata:
  name: grafana-np-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  ports:
  - port: 3000 # Grafana's default port
    targetPort: 3000 # The port Grafana container is listening on
    nodePort: 32000 # Exposed NodePort (must be between 30000-32767)
