apiVersion: v1
kind: Service
metadata:
  name: grafana-lb-svc
spec:
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
