apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: inspekt-labs-task
  ports:
  - protocol: TCP
    port: 80 # Service port
    targetPort: 8018 # Container port
  type: LoadBalancer # Or ClusterIP, NodePort.
